/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guessgame;

import javax.swing.text.DefaultCaret;

/**
 *
 * @author federico
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    PlayerGuess playerguess = new PlayerGuess();
    PCGuess pcguess = new PCGuess();

    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bigger = new javax.swing.JButton();
        smaller = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        Startpc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        computerguessconsole = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        write_number = new javax.swing.JTextField();
        answernumber = new javax.swing.JButton();
        startplayer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        playerguessconsole = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adivinanza de números");
        setResizable(false);

        jTabbedPane2.setRequestFocusEnabled(false);

        jLabel2.setText("Now, I'll guess your number!");

        bigger.setText("It's bigger");
        bigger.setEnabled(false);
        bigger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biggerActionPerformed(evt);
            }
        });

        smaller.setText("It's smaller");
        smaller.setEnabled(false);
        smaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallerActionPerformed(evt);
            }
        });

        equal.setText("That's my number!");
        equal.setEnabled(false);
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        Startpc.setText("Start");
        Startpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartpcActionPerformed(evt);
            }
        });

        computerguessconsole.setColumns(20);
        computerguessconsole.setRows(5);
        jScrollPane1.setViewportView(computerguessconsole);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(smaller)
                                .addGap(18, 18, 18)
                                .addComponent(equal)
                                .addGap(28, 28, 28)
                                .addComponent(bigger))
                            .addComponent(Startpc))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Startpc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smaller)
                    .addComponent(equal)
                    .addComponent(bigger))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Computer guess my number", jPanel2);

        jLabel1.setText("You have to guess my number now!. Click \"Start\" to begin!");

        write_number.setEnabled(false);
        DefaultCaret caret = (DefaultCaret)write_number.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        write_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                write_numberActionPerformed(evt);
            }
        });

        answernumber.setEnabled(false);
        answernumber.setText("Answer");
        answernumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answernumberActionPerformed(evt);
            }
        });

        startplayer.setText("Start");
        startplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startplayerActionPerformed(evt);
            }
        });

        playerguessconsole.setColumns(20);
        playerguessconsole.setRows(5);
        jScrollPane2.setViewportView(playerguessconsole);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(startplayer)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(write_number)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answernumber))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startplayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(write_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answernumber))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Guess number to my computer", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void write_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_write_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_write_numberActionPerformed

    private void answernumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answernumberActionPerformed
        try {
            int nro = Integer.parseInt(write_number.getText());
            playerguessconsole.append("You've writed: " + nro + "\n");
            playerguessconsole.append(playerguess.Guessnumber(nro));
            if (nro == playerguess.getnumber()) {
                playerguessconsole.append("-------\nClick to 'Start' if you wanna play again...\n-------\n");
                write_number.setText("");
                write_number.setEnabled(false);
                answernumber.setEnabled(false);
                startplayer.setText("Start");
            }
        } catch (NumberFormatException e) {
            playerguessconsole.append("You must write a number\n");
        }

    }//GEN-LAST:event_answernumberActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        Startpc.setText("Start");
        smaller.setEnabled(false);
        equal.setEnabled(false);
        bigger.setEnabled(false);
        computerguessconsole.append(pcguess.GuessHumanNumber(2) + "\n");
    }//GEN-LAST:event_equalActionPerformed

    private void StartpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartpcActionPerformed

        if (Startpc.getText() == "Start") {
            Startpc.setText("Surrender");
            smaller.setEnabled(true);
            equal.setEnabled(true);
            bigger.setEnabled(true);
            computerguessconsole.append("Let's see...\n");
            computerguessconsole.append("I think it's " + pcguess.Randomizenumber() + "\n");
        } else {
            Startpc.setText("Start");
            computerguessconsole.append("¿Are you going to surrender early?Ok. I win!\n");
            smaller.setEnabled(false);
            equal.setEnabled(false);
            bigger.setEnabled(false);
        }
    }//GEN-LAST:event_StartpcActionPerformed

    private void smallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallerActionPerformed
        // TODO add your handling code here:
        computerguessconsole.append(pcguess.GuessHumanNumber(1) + "\n");
    }//GEN-LAST:event_smallerActionPerformed

    private void biggerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biggerActionPerformed
        // TODO add your handling code here:
        computerguessconsole.append(pcguess.GuessHumanNumber(3) + "\n");
    }//GEN-LAST:event_biggerActionPerformed

    private void startplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startplayerActionPerformed

        if (startplayer.getText() == "Start") {
            startplayer.setText("Surrender");
            write_number.setEnabled(true);
            answernumber.setEnabled(true);
            playerguess.thinknumber();
            playerguessconsole.append("Ok... Tell me the first number\n");
        } else {
            startplayer.setText("Surrender");
            write_number.setEnabled(false);
            write_number.setText("");
            answernumber.setEnabled(false);
            playerguessconsole.append("¿Are you going to surrender early?Ok. I win!\n");
        }
    }//GEN-LAST:event_startplayerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Startpc;
    private javax.swing.JButton answernumber;
    private javax.swing.JButton bigger;
    private javax.swing.JTextArea computerguessconsole;
    private javax.swing.JButton equal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea playerguessconsole;
    private javax.swing.JButton smaller;
    private javax.swing.JButton startplayer;
    private javax.swing.JTextField write_number;
    // End of variables declaration//GEN-END:variables
}
